name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - name: Install esy
        run: npm install -g esy
      - name: Try to restore dependencies cache
        id: restore-cache
        uses: actions/cache@v2
        with:
          path: _export
          key: ${{ runner.os }}-esy-${{ hashFiles('esy.lock/index.json') }}
          restore-keys: |
            ${{ runner.os }}-latest-
      - name: Esy install
        run: esy install
      - name: Import Cache
        run: |
          esy import-dependencies _export
          rm -rf _export
      - name: Esy build
        run: esy build
      - name: Exporting dependencies
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: esy export-dependencies
      - name: Run tests
        run: esy test
